name: Run Tests and Generate Allure Report

on:
  push

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Используем maven репозиторий
        uses: actions/checkout@v3

      - name: Clean project
        run: mvn clean

      - name: Запуск тестов
        run: mvn test
        continue-on-error: true

      - name: Генерация Allure отчета
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-report/history

      - name: Развертывание на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/allure-maven-plugin
          publish_branch: gh-pages
