name: Run Tests and Generate Allure Report

on:
  push

jobs:
  Run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Установка Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Установка Allure CLI
        run: |
          curl -sL "https://github.com/allure-framework/allure2/releases/latest/download/allure-2.23.0.tgz" | tar -xz -C /opt/
          echo "/opt/allure-2.23.0/bin" >> $GITHUB_PATH

      - name: Clean project
        run: mvn clean

      - name: Запуск тестов
        run: mvn test
        continue-on-error: true

      - name: Генерация Allure отчета
        run: |
          allure generate target/allure-results -o target/allure-report
          allure serve target/allure-results

      - name: Развертывание на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./target/site/allure-maven-plugin
          publish_branch: gh-pages
